# Generated by Django 6.0.1 on 2026-01-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Detective Fiction', 'Detective Fiction'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Historical Fiction', 'Historical Fiction'), ('Adventure', 'Adventure')], max_length=255, null=True),
        ),
    ]
