# Generated by Django 5.1.2 on 2026-02-13 13:16

from django.db import migrations


def seed_quest_templates(apps, schema_editor):
    QuestTemplate = apps.get_model("bookapp", "QuestTemplate")
    templates = [
        # Личные задания
        {
            "title": "Читательский марафон",
            "description": "Прочитайте книгу сегодня",
            "quest_type": "read_books",
            "quest_scope": "personal",
            "target_count": 1,
        },
        {
            "title": "Активный читатель",
            "description": "Оставьте комментарии к книгам",
            "quest_type": "create_comments",
            "quest_scope": "personal",
            "target_count": 3,
        },
        {
            "title": "Обсуждение",
            "description": "Ответьте на комментарии других читателей",
            "quest_type": "reply_comments",
            "quest_scope": "personal",
            "target_count": 2,
        },
        {
            "title": "Щедрость",
            "description": "Разместите призы на доске",
            "quest_type": "place_rewards",
            "quest_scope": "personal",
            "target_count": 1,
        },
        {
            "title": "Книжный червь",
            "description": "Прочитайте несколько книг",
            "quest_type": "read_books",
            "quest_scope": "personal",
            "target_count": 2,
        },
        {
            "title": "Комментатор",
            "description": "Оставьте много комментариев",
            "quest_type": "create_comments",
            "quest_scope": "personal",
            "target_count": 5,
        },
        # Групповые задания
        {
            "title": "Читательский марафон (группа)",
            "description": "Прочитайте книгу сегодня",
            "quest_type": "read_books",
            "quest_scope": "group",
            "target_count": 10,
        },
        {
            "title": "Активный читатель (группа)",
            "description": "Оставьте комментарии к книгам",
            "quest_type": "create_comments",
            "quest_scope": "group",
            "target_count": 30,
        },
        {
            "title": "Обсуждение (группа)",
            "description": "Ответьте на комментарии других читателей",
            "quest_type": "reply_comments",
            "quest_scope": "group",
            "target_count": 20,
        },
        {
            "title": "Щедрость (группа)",
            "description": "Разместите призы на доске",
            "quest_type": "place_rewards",
            "quest_scope": "group",
            "target_count": 10,
        },
        {
            "title": "Книжный червь (группа)",
            "description": "Прочитайте несколько книг",
            "quest_type": "read_books",
            "quest_scope": "group",
            "target_count": 20,
        },
        {
            "title": "Комментатор (группа)",
            "description": "Оставьте много комментариев",
            "quest_type": "create_comments",
            "quest_scope": "group",
            "target_count": 50,
        },



    ]
    for t in templates:
        QuestTemplate.objects.get_or_create(title=t["title"], defaults=t)




class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_quest_templates),
    ]
