# Generated by Django 5.1.2 on 2026-01-18 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='reading_group_img'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='reading_groups_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_groups_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
