# Generated by Django 5.1.2 on 2026-01-18 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_readinggroup_featured_image_readinggroup_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='reading_groups_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
