# Generated by Django 6.0.1 on 2026-01-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_readinggroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinggroup',
            options={},
        ),
        migrations.RenameField(
            model_name='readinggroup',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='readinggroup',
            name='published_date',
        ),
    ]
