# Generated by Django 5.1.2 on 2026-01-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_alter_readinggroup_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinggroup',
            options={'ordering': ['-created_at']},
        ),
    ]
