# Generated by Django 5.1.2 on 2026-01-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_readinggroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
