# Generated by Django 5.1.2 on 2026-02-07 12:24

import bookapp.models
import bookapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_book_book_author_alter_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_file',
            field=models.FileField(blank=True, null=True, upload_to=bookapp.models.UniqueFileNameGenerator('epub_files/'), validators=[bookapp.validators.validate_epub_file_extension, bookapp.validators.validate_epub_file_size, bookapp.validators.validate_file_is_not_empty]),
        ),
        migrations.AlterField(
            model_name='book',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=bookapp.models.UniqueFileNameGenerator('book_img/')),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=bookapp.models.UniqueFileNameGenerator('profile_img/')),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=bookapp.models.UniqueFileNameGenerator('reading_group_img/')),
        ),
        migrations.AlterField(
            model_name='rewardtemplate',
            name='image',
            field=models.ImageField(upload_to=bookapp.models.UniqueFileNameGenerator('rewards/'), verbose_name='Изображение'),
        ),
    ]
