# Generated by Django 5.1.2 on 2026-02-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_remove_quest_is_active_alter_book_epub_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quest_type', models.CharField(choices=[('read_books', 'Прочитать книги'), ('create_comments', 'Оставить комментарии'), ('reply_comments', 'Ответить на комментарии'), ('place_rewards', 'Разместить призы')], max_length=50, verbose_name='Тип задания')),
                ('target_count', models.PositiveIntegerField(help_text='Сколько нужно выполнить действий', verbose_name='Целевое количество')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные шаблоны не используются при генерации', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон задания',
                'verbose_name_plural': 'Шаблоны заданий',
                'ordering': ['-created_at'],
            },
        ),
    ]
