# Generated by Django 5.1.2 on 2026-02-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_seed_quest_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='questtemplate',
            name='quest_scope',
            field=models.CharField(choices=[('personal', 'Личное'), ('group', 'Групповое')], default='personal', help_text='Для личных или групповых заданий', max_length=20, verbose_name='Область применения'),
        ),
    ]
